In [5]:
import numpy as np
import tools
import aug

data = np.load("../data/MB_3DP/2/data.npy").astype(np.float32)


print(data.shape)
# N, C, T, V, M
# N, M, V, C, T
N, C, T, V, M = data.shape
# data = np.transpose(data, (0, 4, 3, 1, 2))

# data[0] = aug.gaussian_noise(data[0])
# data[0] = aug.random_translation(data[0])
data = np.transpose(data, (0, 4, 3, 1, 2))
data = data * 0.9

data[:, 1, :, 0, :] = data[:, 1, :, 0, :] - 0.4
data[:, 0, :, 0, :] = data[:, 0, :, 0, :] + 0.4

tools.motion2video_3d_two(data[1000, :, : , :, :300], save_path=f"a.mp4", fps=5, view=[15, 105])
# tools.motion2video_3d(data[0, 1, : , :, :300], save_path=f"b.mp4", fps=5, view=[15, 105])

(31200, 3, 16, 17, 2)


100%|██████████| 16/16 [00:02<00:00,  6.30it/s]


In [ ]:
import numpy as np
import tools

data = np.load("../data/MB_3DP/2/data.npy")


print(data.shape)
# N, C, T, V, M
# N, M, V, C, T
N, C, T, V, M = data.shape
data = np.transpose(data, (0, 4, 3, 1, 2))



tools.motion2video_3d(data[0, 0, : , :, :300], save_path=f"a.mp4", fps=5, view=[15, 105])



# N, M, T, V, C
# N, M, V, C, T
# N, M, T, V, C = data.shape
# data = np.transpose(data, (0, 1, 3, 4, 2))

# N, T, V, C
# N, V, C, T
# data = np.transpose(data, (0, 2, 3, 1))

# a = (N//4)*0
# tmp = data[:, :, :, 0, :].copy()
# tmp1 = data[:, :, :, 1, :].copy()
# data[:, :, :, 0, :] = -1 * tmp
# data[:, :, :, 1, :] = -1 * data[:, :, :, 2, :]
# data[:, :, :, 2, :] = -1 * tmp1
# data[:, :, :, 2, :] = data[:, :, :, 2, :]
# motion2video_3d(data[a+301, 0, : , :, :], save_path="res.mp4", fps=2)


In [ ]:
import numpy as np
import tools

# data1 = np.load("../data/normarized_data/MB_3DP.npy")
# data2 = np.load("../data/normarized_data/SMPL2H36M.npy")
data1 = np.load("../data/normarized_data/MB_3DP.npy")
data2 = np.load("../data/normarized_data/smpl2h36m2.npy")

print(data1.shape)
# N, C, T, V, M
# N, M, V, C, T
N, C, T, V, M = data1.shape
data1 = np.transpose(data1, (0, 4, 3, 1, 2))
data2 = np.transpose(data2, (0, 4, 3, 1, 2))

# N, M, T, V, C = data1.shape
# data1 = np.transpose(data1, (0, 1, 3, 4, 2))


a = (N//4)*2
print(a)
tools.motion2video_3d(data1[a+40, 0, : , :, :300:100], save_path="mb.mp4", fps=5, view=[85, 180])
tools.motion2video_3d(data2[a+50, 0, : , :, :300:100], save_path="sm.mp4", fps=5, view=[85, 180])
# tools.motion2video_3d(data3[a+6, 0, : , :, :300:3], save_path="res3.mp4", fps=5, view=[20, 90])


# motion2video_3d(data[a+301, 0, : , :, :], save_path="res.mp4", fps=2)


In [1]:
import numpy as np
import tools
import os

data = np.load("../data/normarized_data/MB_3DP.npy")
N_time = np.load("../data/N_Time.npy")
print(data.shape)
n, c, t, v, m = data.shape
data = np.transpose(data, (0, 4, 3, 1, 2))

for i in range(1, 3):
    for j in range(2, 3):
        for k in range(1, 53):
            for l in range(1, 4):
                for m in range(1, 3):
                    idx = (312 * (i-1)) + (156 *  (j-1)) + (3 * (k - 1)) + l - 1
                    if not os.path.exists(f'output/all_3d_video/{i}-{j}-{k}-{l}-{m}.mp4'):
                        tools.motion2video_3d(data[idx, m-1, :, :, :N_time[idx]:8], f'output/all_3d_video/{i}-{j}-{k}-{l}-{m}.mp4', view=[15, 105], fps=15)
                    else:
                        print('file is existed')
                        
                idx = idx + 1

(624, 3, 861, 17, 2)
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
file is existed
fil

 43%|████▎     | 37/87 [00:06<00:07,  6.42it/s]

In [14]:
import numpy as np
from tools import motion2video_3d

data = np.load('kondo.npy')
data = data * 10
print(data[2])
# T, V, C -> (V, C, T) 
data = np.transpose(data, (1, 2, 0))
motion2video_3d(data[:, :, :100], 'kondo.mp4', fps=1, view=[15, 105])

[[-0.          0.          0.91910891]
 [-0.65267697 -0.12848147  0.24939947]
 [-0.50924867 -0.13201121  0.10843322]
 [-0.39595064 -0.12222155  0.        ]
 [-0.73015317 -0.1155978   0.33128239]
 [-0.60493745 -0.12306696  0.1842279 ]
 [-0.50919618 -0.11563305  0.06373659]
 [-0.80979861 -0.11950666  0.46306949]
 [-0.91924593 -0.1172772   0.67947879]
 [-0.95141634 -0.11000998  0.77070683]
 [-0.96291989 -0.10989704  0.80871582]
 [-0.94287321 -0.10132186  0.74119754]
 [-0.88325351 -0.09131195  0.55997621]
 [-0.79815187 -0.09967695  0.40418092]
 [-0.8808548  -0.12510492  0.59988711]
 [-0.75169832 -0.12608697  0.36330629]
 [-0.66348389 -0.12619133  0.24052069]]


  2%|▏         | 2/100 [00:00<00:19,  4.94it/s][rawvideo @ 0x6aa4740] Stream #0: not enough frames to estimate rate; consider increasing probesize
[swscaler @ 0x6abc6c0] Warning: data is not aligned! This can lead to a speed loss
100%|██████████| 100/100 [00:19<00:00,  5.16it/s]
